# Generated by Django 5.2.7 on 2026-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Date/Time '),
        ),
    ]
