# Generated by Django 5.2.7 on 2026-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('CNT', 'Central'), ('DEV', 'Development'), ('QNA', 'QnA'), ('TCH', 'Technology'), ('COK', 'Cooking'), ('WNS', 'World News'), ('ECO', 'Economics')], default='CNT', max_length=3),
        ),
    ]
