# Generated by Django 5.2.7 on 2026-01-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_post_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='category',
        ),
    ]
