# Generated by Django 5.2.7 on 2026-01-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_rename_post_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CNT', 'Central'), ('DEV', 'Development'), ('QNA', 'QnA'), ('TCH', 'Technology'), ('WNS', 'World News'), ('ECO', 'Economics'), ('ART', 'Art'), ('ENT', 'Entertainment'), ('VGZ', 'Video Games')], default='CNT', max_length=3),
        ),
    ]
