# Generated by Django 5.2.7 on 2026-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_total_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
