# Generated by Django 5.2.7 on 2026-01-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_alter_post_current_total_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='current_total_size',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
