# Generated by Django 5.2.7 on 2026-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_alter_post_current_total_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='current_total_size',
            field=models.FloatField(default=0, null=True),
        ),
    ]
