# Generated by Django 5.2.7 on 2025-11-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_account',
        ),
    ]
