# Generated by Django 5.2.7 on 2026-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_friendshiprequest_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
