# Generated by Django 5.2.7 on 2026-02-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_post_count_userprofile_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bubbles',
            field=models.PositiveIntegerField(default=200, null=True),
        ),
    ]
