# Generated by Django 5.2.7 on 2026-02-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_bubbles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bubbles',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='BZ',
            field=models.PositiveIntegerField(default=200, null=True),
        ),
    ]
