# Generated by Django 5.2.7 on 2026-02-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userprofile_bz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='BZ',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
