# Generated by Django 5.2.7 on 2026-02-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='goal',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
